#!/usr/bin/env ruby
Dir.glob("./*.gem").each { |path| `rm #{path}` }
puts `gem uninstall -x quick_class`
puts `gem build quick_class.gemspec`
Dir.glob("./*.gem").each { |path| puts `gem install -f #{path}` }
